# Generated by Django 5.2.5 on 2025-08-15 15:15

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactersheet',
            name='sidebar',
            field=tinymce.models.HTMLField(default='<table style="border-collapse: collapse; width: 100.015%; height: 179.2px;" border="1"><colgroup><col style="width: 49.9242%;"><col style="width: 49.9242%;"></colgroup>\n                                                <tbody>\n                                                <tr style="height: 22.4px;">\n                                                <th style="height: 22.4px;">Species</th>\n                                                <td style="height: 22.4px;">&nbsp;</td>\n                                                </tr>\n                                                <tr style="height: 22.4px;">\n                                                <th style="height: 22.4px;">Age</th>\n                                                <td style="height: 22.4px;">&nbsp;</td>\n                                                </tr>\n                                                <tr style="height: 22.4px;">\n                                                <th style="height: 22.4px;">Birthday</th>\n                                                <td style="height: 22.4px;">&nbsp;</td>\n                                                </tr>\n                                                <tr style="height: 22.4px;">\n                                                <th style="height: 22.4px;">Height</th>\n                                                <td style="height: 22.4px;">&nbsp;</td>\n                                                </tr>\n                                                <tr style="height: 22.4px;">\n                                                <th style="height: 22.4px;">Weight</th>\n                                                <td style="height: 22.4px;">&nbsp;</td>\n                                                </tr>\n                                                <tr style="height: 22.4px;">\n                                                <th style="height: 22.4px;">Body Type</th>\n                                                <td style="height: 22.4px;">&nbsp;</td>\n                                                </tr>\n                                                <tr style="height: 22.4px;">\n                                                <th style="height: 22.4px;">Gender</th>\n                                                <td style="height: 22.4px;">&nbsp;</td>\n                                                </tr>\n                                                <tr style="height: 22.4px;">\n                                                <th style="height: 22.4px;">Sexuality</th>\n                                                <td style="height: 22.4px;">&nbsp;</td>\n                                                </tr>\n                                                </tbody>\n                                                </table>'),
        ),
    ]
