# Generated by Django 5.2.5 on 2025-08-11 20:16

import django.db.models.deletion
import social_links_field.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('pronouns', models.CharField(blank=True, max_length=50, null=True)),
                ('bio', models.TextField(blank=True)),
                ('pfp', models.ImageField(blank=True, upload_to='')),
                ('social_links', social_links_field.models.SocialLinksField(default=list)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
