# Generated by Django 5.2.5 on 2025-08-13 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitecode',
            name='is_active',
        ),
    ]
