# Generated by Django 5.2.5 on 2025-08-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_invitecode_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitecode',
            name='is_active_field',
            field=models.BooleanField(default=True),
        ),
    ]
