# Generated by Django 5.2.5 on 2025-08-13 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_invitecode_is_active_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitecode',
            old_name='is_active_field',
            new_name='is_active',
        ),
    ]
