# Generated by Django 5.2.5 on 2025-08-14 16:15

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_is_active_field_invitecode_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=tinymce.models.HTMLField(),
        ),
    ]
