# Generated by Django 5.2.5 on 2025-08-15 20:07

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_userprofile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pfp',
            field=imagekit.models.fields.ProcessedImageField(upload_to='avatars'),
        ),
    ]
